services:
  redis:
    image: redis:8.0-M02-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:17.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=server
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
    environment:
      - SERVER_ADDR=:8080
      - REDIS_ADDR=redis:6379
      - DB_CONN=postgres://user:password@postgres:5432/server?sslmode=disable
      - LOG_LEVEL=-4


volumes:
  pgdata:
